# If you encounter problems while building images for services depending on databases, separately startup databases before running this.

version: '3'

services:
  database-auth:
    image: mysql:8.0.30-debian
    ports:
      - 3307:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
    volumes:
      - auth-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms-auth

  database-faculty:
    image: mysql:8.0.30-debian
    ports:
      - 3308:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
    volumes:
      - faculty-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms-faculty

  database-subject:
    image: mysql:8.0.30-debian
    ports:
      - 3309:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
    volumes:
      - subject-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms-subject

  database-exam:
    image: mysql:8.0.30-debian
    ports:
      - 3310:3306
    volumes:
      - exam-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms-exam

  backend-config-server:
    build:
      context: ./backend/config-server
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    healthcheck:
      test: wget --spider --quiet 'http://localhost:8888/actuator/health/' || exit 1
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      SPRING_PROFILES_ACTIVE: prod, native

  backend-discovery-server:
    build:
      context: ./backend/discovery-server
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    healthcheck:
      test: wget --spider --quiet 'http://localhost:8761/actuator/health/' || exit 1
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      backend-config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

  backend-api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      backend-discovery-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

  backend-auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      backend-discovery-server:
        condition: service_healthy
      database-auth:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

  backend-faculty-service:
    build:
      context: ./backend/faculty-service
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      backend-discovery-server:
        condition: service_healthy
      database-faculty:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

  backend-subject-service:
    build:
      context: ./backend/subject-service
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    depends_on:
      backend-discovery-server:
        condition: service_healthy
      database-subject:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

  backend-exam-service:
    build:
      context: ./backend/exam-service
      dockerfile: Dockerfile
    ports:
      - 8084:8084
    depends_on:
      backend-discovery-server:
        condition: service_healthy
      database-exam:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      PRODUCTION: true

volumes:
  auth-data:
  faculty-data:
  subject-data:
  exam-data:
